---

- name: Download and install Composer
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Download and install Composer
      shell: |
        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
        HASH=`curl -sS https://composer.github.io/installer.sig` && \
        php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;" && \
        sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        executable: /bin/bash
      tags: 
        - composer
