---

- name: Install PHP 8.2
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Install PHP 8.2
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - lsb-release
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags: 
        - php

    - name: Add PHP repository
      apt_repository:
        repo: 'ppa:ondrej/php'
      when: ansible_distribution == 'Ubuntu'
      tags: 
        - php

    - name: Install PHP 8.2 FPM and Apache mod_fcgid
      apt:
        name:
          - php8.2-fpm
          - libapache2-mod-fcgid
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags: 
        - php


    - name: Enable Apache proxy_fcgi and setenvif modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy_fcgi
        - setenvif
      when: ansible_service_mgr == 'systemd'
      tags: 
        - php

    - name: Enable PHP 8.2 FPM Apache configuration
      template:
        src: php-fpm.conf.j2  # Path to your custom Apache configuration template
        dest: /etc/apache2/conf-available/php8.2-fpm.conf
      notify: Restart Apache
      when: ansible_service_mgr == 'systemd'
      tags: 
        - php

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      when: ansible_service_mgr == 'systemd'
      tags: 
        - php

    - name: Install PHP CLI and unzip
      apt:
        name:
          - php-cli
          - unzip
        state: present
      tags: 
        - composer






