---

- name: Install Node.js on Ubuntu
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Install curl and software-properties-common
      apt:
        name:
          - curl
          - software-properties-common
        state: present

    - name: Add Node.js repository
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

    - name: Install Node.js
      apt:
        name: nodejs
        update_cache: yes
        state: present
