---

- name: Install and Configure Web Server
  hosts: your_server
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - nodejs
          - php8.2-fpm
          - nginx
          - mariadb-server
          - composer
          - git
          - python3-mysqldb

    - name: Ensure services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php8.2-fpm
        - mariadb
