---

- name: Install MariaDB
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
      tags: 
        - mariadb
