---

- name: Install NGINX
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      tags: 
        - nginx
