---

- name: Install PHP 8.2 and Apache module on Ubuntu
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add ondrej/php PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install PHP 8.2 and Apache module
      apt:
        name:
          - php8.2
          - libapache2-mod-php8.2
        state: present

    - name: Install SQLite3 for PHP 8.2
      apt:
        name: php8.2-sqlite3
        state: present

    - name: Restart PHP FPM service for PHP 8.2
      systemd:
        name: php8.2-fpm
        state: restarted

    - name: Enable PHP 8.2 XML extension
      command: phpenmod -v 8.2 xml
      become: yes

    - name: Enable PHP 8.2 cURL extension
      command: phpenmod -v 8.2 curl
      become: yes

    - name: Enable PHP 8.2 DOM extension
      command: phpenmod -v 8.2 dom
      become: yes

    - name: Enable PHP 8.2 SQLite3 extension
      command: phpenmod -v 8.2 sqlite3
      become: yes